V 0.2.0 page markup
sweeser/healthy_mama-layout pull request #1
Opened 2024-08-01 08:44 UTC by sweeser

2024-08-02 12:05 UTC, acherenkovcian approved these changes

2024-08-02 12:05 UTC, acherenkovcian commented on index.html
> +            <img class="gallery__image" src="./images/gallery-image-1.png" alt="">
На твое усмотрение, можно сделать картинки по отдельности, можно все это собрать в одну картинку

2024-08-02 12:05 UTC, acherenkovcian commented on index.html
> +        <ul class="footer__list">
🔴это разные списки с разными стилями

2024-08-02 12:07 UTC, artcherenkov requested changes
описал в комментах. работа хорошая, критических замечаний нет, только парочка для SEO

2024-08-05 06:26 UTC, artcherenkov reviewed
По верстке все хорошо, осталось разобраться с доступностью (заполнение `alt`, `aria-label` и прочее). Я мог в некоторых места ввести тебя в заблуждение по поводу правил заполнения `alt`, поэтому бегло ознакомься с докой, чтобы точно не запутаться. 
1. Что такое доступность https://doka.guide/a11y/chto-takoe-a11y/
2. Инструменты для улучшения доступности сайта https://doka.guide/a11y/aria-intro/
3. Как правильно задавать описание элементов для доступности https://doka.guide/a11y/accessible-names-and-descs/
4. Как работают скринридеры https://doka.guide/a11y/screenreaders/

2024-08-05 06:26 UTC, artcherenkov commented on index.html
> +                <button class="products__slider-button products__slider-button_direction_right"><img src="./images/slider-button-right-promo.svg" alt="Изображение кнопки, которая переключает слайд вп
+ про `aria-label`

🔴 вспомнил один момент, давай добавим атрибут `aria-label` для тега кнопки, а `alt` для картинки оставим пустым. Подробнее о том, как заполнять [тут](https://doka.guide/a11y/aria-label/).

2024-08-05 06:26 UTC, artcherenkov commented on index.html
> +        <ul class="footer__navigation-list">
✅ гуд

2024-08-06 07:07 UTC, artcherenkov approved these changes

2024-08-06 07:11 UTC, merged